version: "3.8"

services:

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - car-booking-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - car-booking-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: unless-stopped
    volumes:
      - ./kafka:/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
    networks:
      - car-booking-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  spark:
    image: apache/spark:3.4.2
    container_name: spark-master
    restart: unless-stopped
    ports:
      - "8082:8080"
      - "7077:7077"
      - "4040:4040"
    depends_on:
      - kafka
    volumes:
      - C:/Users/gautam/car-booking-pipeline/spark:/opt/spark-apps
      - C:/Users/gautam/car-booking-pipeline/config:/opt/config
      - C:/Users/gautam/car-booking-pipeline/reports:/opt/reports
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    networks:
      - car-booking-network

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    networks:
      - car-booking-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - car-booking-network

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: booking
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/mysql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - car-booking-network

  #jenkins:
    #image: jenkins/jenkins:lts
    #container_name: jenkins
    #user: root
    #restart: unless-stopped
    #  - "8080:8080"
    #  - "50000:50000"
    #volumes:
    #  - jenkins_home:/var/jenkins_home
    #  - /var/run/docker.sock:/var/run/docker.sock
    #networks:
    #  - car-booking-network
  
  great_expectations:
    build: ./great_expectations
    container_name: great_expectations
    restart: unless-stopped
    volumes:
      - ./great_expectations:/ge
      - C:/Users/gautam/car-booking-pipeline/config:/opt/config
      - C:/Users/gautam/car-booking-pipeline/reports:/opt/reports
      - ./spark/lib:/opt/spark/lib
    depends_on:
      - postgres
    command: tail -f /dev/null
    healthcheck:
      test: ["CMD", "python", "-c", "import great_expectations"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - car-booking-network

networks:
  car-booking-network:
    driver: bridge

volumes:
  #jenkins_home:
  postgres_data:
  mysql_data: